### ISSUE TITLE
Are you able to create pull request?

### ISSUE THREAD

**Issue by CliqueAdmin** [Mahi451/AppQuipo#2]
@Mahi451

**Comment by Mahi451** [comment]
not yet

**Comment by Mahi451** [comment]
yes

**Comment by CliqueAdmin** [comment]
I can't see the pull request.

**Comment by CliqueAdmin** [comment]
![image](https://user-images.githubusercontent.com/57764284/109069349-f494b580-76a5-11eb-9909-d84fc40fa83b.png)

**Comment by CliqueAdmin** [comment]
I am checking in appquip https://github.com/Mahi451/AppQuipo

**Comment by CliqueAdmin** [comment]
I think I am looking at the wrong repository.

**Comment by CliqueAdmin** [comment]
Closing the issue as I am able to see the comment.
